# Generated by Django 4.1 on 2022-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalnoboy', '0003_alter_video_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='create_at',
            field=models.DateField(),
        ),
    ]
