# Generated by Django 4.1 on 2022-08-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalnoboy', '0006_stranic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stranic',
            old_name='sttitle',
            new_name='str_title',
        ),
    ]
