# Generated by Django 4.1 on 2022-08-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalnoboy', '0007_rename_sttitle_stranic_str_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stranic',
        ),
    ]
