# Generated by Django 4.1 on 2022-08-10 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalnoboy', '0008_delete_stranic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stranic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_title', models.CharField(max_length=70, verbose_name='Страничка')),
                ('title', models.CharField(max_length=70, verbose_name='Оглавление')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('file', models.FileField(upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео')),
            ],
        ),
    ]
