# Generated by Django 4.1 on 2022-08-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalnoboy', '0009_stranic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stranic',
        ),
    ]
