# Generated by Django 4.1 on 2022-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalnoboy', '0013_stranic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stranic',
            name='id_n',
            field=models.CharField(max_length=20, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='stranic',
            name='title_ad',
            field=models.TextField(verbose_name='адрес ссылка'),
        ),
        migrations.AlterField(
            model_name='stranic',
            name='url_ad',
            field=models.URLField(verbose_name='адрес'),
        ),
    ]
