# Generated by Django 4.1 on 2022-08-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalnoboy', '0014_alter_stranic_id_n_alter_stranic_title_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stranic',
            name='title_ad',
            field=models.TextField(verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='stranic',
            name='url_ad',
            field=models.URLField(verbose_name='адрес ссылка'),
        ),
    ]
